[package]
name = "steve"
version = "0.1.0"
authors = ["Leif Grele <lkgrele@us.ibm.com>"]

[dependencies]
serde="0.7.0"
serde_json="0.7.0"
hubcaps="0.2.2"
hyper="0.9.0"
regex="0.1.71"
lazy_static="0.2.1"
rustc-serialize="0.3"
toml="0.1"

[dependencies.afterparty]
path="../afterparty"
